import { execSync } from "child_process";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

console.log("🔄 Supabase Schema Resync");
console.log("=".repeat(50) + "\n");

// Step 1: Fetch remote schema
console.log("1️⃣  Fetching remote schema...");
try {
  // This would require Supabase CLI to be logged in
  // For now, we'll create a migration based on known schema
  console.log("   ℹ️  Schema fetch requires Supabase CLI login");
  console.log("   Run: supabase login");
  console.log("   Then: supabase db dump --project-id bwlmlniotyrjttglbjrl\n");
} catch (err) {
  console.warn("   ⚠️  Could not fetch remote schema");
}

// Step 2: Compare with migrations
console.log("2️⃣  Comparing with local migrations...");
const migrationsDir = join(projectRoot, "supabase", "migrations");
if (!existsSync(migrationsDir)) {
  console.error("   ❌ Migrations directory not found");
  process.exit(1);
}

const migrations = readdirSync(migrationsDir)
  .filter(f => f.endsWith(".sql"))
  .sort();

console.log(`   Found ${migrations.length} migration files`);

// Step 3: Generate unified migration
console.log("\n3️⃣  Generating unified migration...");
const timestamp = new Date().toISOString().replace(/[-:]/g, "").split(".")[0].replace("T", "");
const unifiedMigration = join(migrationsDir, `${timestamp}_unified_schema_fix.sql`);

const unifiedSQL = `-- Unified Schema Fix Migration
-- This migration ensures all required columns exist
-- Generated by schema-resync.mjs

DO $$
BEGIN
    -- Business table fields
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'verification_notes') THEN
        ALTER TABLE public.businesses ADD COLUMN verification_notes TEXT;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'island') THEN
        ALTER TABLE public.businesses ADD COLUMN island TEXT;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'gallery_images') THEN
        ALTER TABLE public.businesses ADD COLUMN gallery_images TEXT[];
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'services') THEN
        ALTER TABLE public.businesses ADD COLUMN services TEXT[];
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'opening_hours') THEN
        ALTER TABLE public.businesses ADD COLUMN opening_hours JSONB;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'average_rating') THEN
        ALTER TABLE public.businesses ADD COLUMN average_rating NUMERIC(3,2) DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'total_reviews') THEN
        ALTER TABLE public.businesses ADD COLUMN total_reviews INTEGER DEFAULT 0;
    END IF;
    
    -- Ensure latitude and longitude are NUMERIC
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'latitude' AND data_type != 'numeric') THEN
        ALTER TABLE public.businesses ALTER COLUMN latitude TYPE NUMERIC(10,8);
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'longitude' AND data_type != 'numeric') THEN
        ALTER TABLE public.businesses ALTER COLUMN longitude TYPE NUMERIC(11,8);
    END IF;
    
    RAISE NOTICE 'Unified schema fix complete';
END $$;
`;

writeFileSync(unifiedMigration, unifiedSQL);
console.log(`   ✅ Created: ${unifiedMigration.split(/[/\\]/).pop()}\n`);

// Step 4: Rebuild types
console.log("4️⃣  Rebuilding Supabase types...");
try {
  execSync(
    'npx supabase gen types typescript --project-id "bwlmlniotyrjttglbjrl" > src/types/supabase.types.ts',
    { cwd: projectRoot, stdio: "inherit" }
  );
  console.log("   ✅ Types regenerated\n");
} catch (err) {
  console.warn("   ⚠️  Could not regenerate types");
  console.warn("   Run manually: npx supabase gen types typescript --project-id bwlmlniotyrjttglbjrl\n");
}

// Step 5: Clear local schema caches
console.log("5️⃣  Clearing local schema caches...");
const cacheDirs = [
  join(projectRoot, "node_modules", ".vite"),
  join(projectRoot, ".vite")
];

cacheDirs.forEach(dir => {
  if (existsSync(dir)) {
    try {
      require("fs").rmSync(dir, { recursive: true, force: true });
      console.log(`   ✓ Cleared: ${dir.replace(projectRoot, ".")}`);
    } catch (err) {
      // Ignore
    }
  }
});
console.log("   ✅ Cache cleared\n");

console.log("✅ Schema resync complete!");
console.log("\nNext steps:");
console.log("   1. Apply migration: supabase db reset --linked");
console.log("   2. Restart dev server: npm run dev");
console.log("=".repeat(50) + "\n");

