// This file is auto-generated by Supabase CLI
// To regenerate: npx supabase gen types typescript --project-id bwlmlniotyrjttglbjrl --schema public
// 
// Note: If CLI is not available, types are maintained in src/integrations/supabase/types.ts

export type { Database } from './types';

